spring:
  application:
    name: emailservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Email Service version 1.0
server:
  port: 21904